### ISSUE TITLE
xterm - ansi - PennMUSH

### ISSUE THREAD

**Issue by stromm** [talvo/potato#452]
There seems to be an issue with the way that Potato is handling the +xterm3 color in it's display. Below is a screen shot of the xterm3 color, along with it's hex and 16bit ansi counterpart.

Tried this on a couple of different clients now and Potato seems to be the only displaying the xterm3 color incorrectly.
![xtermissue](https://cloud.githubusercontent.com/assets/3068849/15630573/c46f0624-2517-11e6-9a09-3f99beadb01b.png)

**Comment by stromm** [comment]
Looks to be defined wrong

http://www.calmar.ws/vim/256-xterm-24bit-rgb-color-chart.html

**Comment by TehomCD** [comment]
Playing around with ansi code for my game, I think I found the issue. If a server sends potato a control code in the format of '\033[38;5;001m' to '\033[38;5;099m', having leading zeroes, you'll see this behavior. If the code is in the format of '\033[38;5;1m' to '033[38;5;99m', it seems to be fine. I have no clue if other clients have similar behavior - I switched to the latter format, and no longer had any issues with Potato, and haven't had anyone complain about their clients unable to see xterm256.

**Comment by talvo** [comment]
@stromm - If memory serves, when I was setting it up originally, I couldn't find a definitive set of colours for the first 16. The spec just says that they're the same as the named 16 ANSI colours, and there's no specific/definitive definition of what those are. I don't remember where I got the ones I used from, but I don't mind changing them.

@TehomCD - To the best of my knowledge, the spec doesn't allow for any leading zeroes on the colour numbers, but if you have a link to any documentation saying otherwise, please let me know.
