### ISSUE TITLE
TLSv1+ not supported

### ISSUE THREAD

**Issue by sypherspace** [talvo/potato#456]
It appears that the Potato client does not support remote servers that force TLSv1 or higher. We encountered this when compiling fuzzball v7 on Debian. It appears that Debian's OpenSSL libraries will shim SSLv3 to TLSv1 server-side, and clients stopped working. As quite a few of our players use Potato, we're in the process of migrating to a new server that will allow us to continue supporting SSLv3 for a time, but the ideal solution would be to enable TLSv1, TLSv1.1, and TLSv1.2 support in the client.

Side note: SSLv3 was officially deprecated by RFC 7568, June 2015.

**Comment by talvo** [comment]
For some reason, SSL2 and SSL3 are enabled by default and TLS1 isn't, not sure. Literally a case of adding '-tls1 1' to enable it, so not a problem.

**Comment by sypherspace** [comment]
Sorry if this sounds ignorant, but is that a client-side invocation, or a code change?

**Comment by talvo** [comment]
Not ignorant at all, I wasn't very clear; it's a code change for me to make, just putting it here in case I don't get around to making it today, so I don't have to go look it up again.

**Comment by sypherspace** [comment]
Lastly, will this enable TLSv1 only, or TLSv1, TLSv1.1, and TLSv1.2 as well?

**Comment by talvo** [comment]
Good question; I had thought it would do them all, but looking further, that seems not to be the case. Newer versions of Tcl's tls package also have -tls1.1 and -tls1.2 options for the respective versions.

(Naturally, Debian still includes an older version that doesn't yet have those.)

I should probably set things up so people can actually choose which protocols they want to allow, rather than just blanket allowing everything (though for now enabling everything will, at least, let people connect.)

At some point letting people do certs would be nice, too, but that's probably low priority enough that it won't happen in this lifetime unless a lot of people clamour for it.

**Comment by talvo** [comment]
(For my own reference - http://tls.sourceforge.net/ for TLS package docs, which helpfully haven't been updated to mention -tls1.1 and -tls1.2 but can be seen in the source at http://tls.cvs.sourceforge.net/viewvc/tls/tls/tls.tcl?revision=1.14&view=markup)

**Comment by talvo** [comment]
Updated to tls 1.6.7 in commit 7b375f816fc090695d0ffa61b53f04042edf1752; tls v1, 1.1 and 1.2 now enabled.
