### ISSUE TITLE
Can't change to Courier font

### ISSUE THREAD

**Issue by vellius** [talvo/potato#461]
Changing fonts(in either the program or world properties) seems to work normally, with one hitch: if I try to set my font as Courier(my preference), the client automatically sets Courier New, instead.  It doesn't matter if I'm trying to change from Courier New to Courier, or from a different font to Courier; it simply can't be set.

**Comment by talvo** [comment]
"Courier" is one of three font names ("Times" and "Helvetica" being the other two) treated specially by Tk, and it seems to be blocking access to actual installed fonts with those names. Raising it as a bug there, so hopefully some time it'll change there and be seen here. :)

(Closing this for now since there's nothing I can actually do about it directly, but I will ~~try and remember to~~ let you know when I hear anything.)
